travis:
  secure:
    BINSTAR_TOKEN: xSeTDpHuROwayPPBonULrpGg/Wb/ZbPfsG27ErvYH7WbrT5EYhW9HnCQhJ5acyBOlOnxEgVIBkM/KMRoJKXO170uGr/j1nhH6eLQU7ZKrIugWurMsROY2HWiZ6oTvdgASI9Zf/8mlcGvmsMmjjbFlXcaCb1O+DbELoq1BKhELUwa73fcWaj4j55s2Z2krtTv0ucGajPi+CHkUlo70+bZA/s3NVvflqNX66lj5epaBPd9VyCsFutUPhsPso+T3JQygFNrk5RNNrDR+a5Zn0aJEUDPEhGo+ijr0dBMxVI7GmBqIL2B7SGkCCXabCKwTLDJy8ZQF5Z6NMqsBIMWQT7RcLqK5MF4qQvdB6Gh/2oZI5aT9QQzYwCPEq7nmcHeL+7uWnhVl6e6YQxEtJBgcL9XF1rGQPOZwi0OEkAeqvNK+752ji3yfQvYOMyV0+Vtkn1IkF4TXi69QP8OS80AlSSKNEIG3MoF7a8BKdMTiMe3CDYLXdj+s9YbnkrxwMclnSXm/hNXEMK9GSqr+M3y3lioh48ZFWDOgT+T4mYaSYr3dJRKDkyggOZaH8iAbEnGBz9NqiKeH0wOHCutEtqu/qYtfJl7x4JQbqB0h+I6xXFTi+bQFTep0yhSTGaASy4DIbjz5creIpKY0quW2kYSJ50vtAFOsA/aFsajWGeL7cCbYU0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
